### ISSUE TITLE
個人todoメモ

### ISSUE THREAD

**Issue by RGBA-CRT** [RGBA-CRT/N64cart#1]
todoのメモ

16MB境界またぎ転送の有無調査
ROMセレクトの外部表示
- LCDとかLEDとか
ROMマッピングの機能強化
ROMFS
usb-uploaderの改善
- patch機能をまじめに考える
- 高速化
  - パケットサイズ変更
  - Verifyスキップ
  - bulk転送（今はどっち？）
- read機能
各バンクにリセットベクタ
- 設計思想的にはいらない
基板起こし
Flash対応
ファーム圧縮

**Comment by RGBA-CRT** [comment]
libusbの更新。ハングアップ対策。
リファクタ

**Comment by RGBA-CRT** [comment]
`
Thread 1 (Thread 3272.0x2d48):
#0  0x77302aac in ntdll!ZwDeviceIoControlFile () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x76498aa4 in SetProcessDynamicEnforcedCetCompatibleRanges () from C:\WINDOWS\System32\KernelBase.dll
#2  0x75affc4b in KERNEL32!DeviceIoControl () from C:\WINDOWS\System32\kernel32.dll
#3  0x61f864c0 in libusbK!LstK_Sync () from C:\WINDOWS\SysWOW64\libusbK.dll
#4  0x61f82eb8 in libusbK!UsbK_ResetPipe () from C:\WINDOWS\SysWOW64\libusbK.dll
#5  0x6b80d2bc in winusbx_clear_halt (sub_api=0x1, dev_handle=0xc0a070, endpoint=0x1)
    at ../../libusb-1.0.26/libusb/os/windows_winusb.c:3148
#6  0x6b81137d in winusb_clear_halt (dev_handle=0xc0a070, endpoint=0x1)
    at ../../libusb-1.0.26/libusb/os/windows_winusb.c:2028
#7  0x6b802cc6 in libusb_clear_halt@8 (dev_handle=0xc0a070, endpoint=0x1) at ../../libusb-1.0.26/libusb/core.c:1801
#8  0x00401571 in bulk_transfer ()
#9  0x00401a11 in rom_write ()
#10 0x0040289f in main ()
#11 0x0040138b in __tmainCRTStartup ()
Backtrace stopped: Cannot access memory at address 0x9b8532e8
gdb-peda$                                             `
